name: highcraft
version: '${project.version}'
main: org.bapr5.highcraft.Highcraft
api-version: '1.20'
commands:
  island:
    description: Your island menu
    usage: /island
    aliases: [/i,/isle,/is,/island]
  menu:
    description: Your island menu
    usage: /menu
    aliases: [ /m,/menu ]
  classes:
    description: Available Classes
    usage: /classes
    aliases: [ /classes ]